-- TeamPulse Supabase Auth mapping.
-- Run after Supabase Auth is enabled. Keep service_role keys only on trusted servers.

create table if not exists public.departments (
  id bigint generated by default as identity primary key,
  name text not null unique,
  code text not null unique,
  manager_id bigint null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique references auth.users(id) on delete cascade,
  full_name text not null,
  email text not null unique,
  role text not null check (role in ('employee', 'manager', 'admin')),
  is_active boolean not null default true,
  manager_id bigint null references public.users(id),
  department_id bigint null references public.departments(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.departments
  add constraint departments_manager_id_fkey
  foreign key (manager_id) references public.users(id);

create table if not exists public.leave_balances (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  year int not null,
  casual_total int not null default 12,
  casual_used int not null default 0,
  sick_total int not null default 10,
  sick_used int not null default 0,
  earned_total int not null default 15,
  earned_used int not null default 0,
  unpaid_used int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_leave_balance_user_year unique (user_id, year)
);

create table if not exists public.leave_requests (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.users(id),
  manager_id bigint null references public.users(id),
  leave_type text not null check (leave_type in ('casual', 'sick', 'earned', 'unpaid')),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'cancelled')),
  start_date date not null,
  end_date date not null,
  days int not null,
  reason text not null,
  manager_comment text null,
  created_at timestamptz not null default now(),
  decided_at timestamptz null
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  recipient_id bigint not null references public.users(id) on delete cascade,
  notification_type text not null check (notification_type in ('info', 'warning', 'approval', 'rejection')),
  title text not null,
  message text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id bigint null references public.users(id),
  action text not null check (action in ('create', 'update', 'delete', 'approve', 'reject', 'login')),
  entity_type text not null,
  entity_id bigint null,
  old_values jsonb null,
  new_values jsonb null,
  ip_address text null,
  created_at timestamptz not null default now()
);

alter table public.users enable row level security;
alter table public.departments enable row level security;
alter table public.leave_balances enable row level security;
alter table public.leave_requests enable row level security;
alter table public.notifications enable row level security;
alter table public.audit_logs enable row level security;

create policy "users can read their TeamPulse profile"
on public.users for select
to authenticated
using (auth_user_id = auth.uid());

create policy "users can read their leave balances"
on public.leave_balances for select
to authenticated
using (exists (
  select 1 from public.users u
  where u.id = leave_balances.user_id and u.auth_user_id = auth.uid()
));

create policy "users can read their notifications"
on public.notifications for select
to authenticated
using (exists (
  select 1 from public.users u
  where u.id = notifications.recipient_id and u.auth_user_id = auth.uid()
));
