-- Zoho-style leave management configuration tables.

create table if not exists public.leave_types (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  description text null,
  is_paid boolean not null default true,
  requires_balance boolean not null default true,
  requires_approval boolean not null default true,
  max_days_per_request int null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.leave_policies (
  id bigint generated by default as identity primary key,
  leave_type_code text not null references public.leave_types(code),
  department_id bigint null references public.departments(id),
  role text null check (role in ('employee', 'manager', 'admin')),
  annual_allowance int not null default 0,
  carry_forward_allowed boolean not null default false,
  max_carry_forward int not null default 0,
  min_notice_days int not null default 0,
  allow_half_day boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.holidays (
  id bigint generated by default as identity primary key,
  name text not null,
  holiday_date date not null,
  department_id bigint null references public.departments(id),
  is_optional boolean not null default false,
  created_at timestamptz not null default now(),
  unique (holiday_date, department_id, name)
);

create index if not exists idx_leave_types_active on public.leave_types (is_active);
create index if not exists idx_leave_policies_scope on public.leave_policies (leave_type_code, department_id, role, is_active);
create index if not exists idx_holidays_date_scope on public.holidays (holiday_date, department_id);

insert into public.leave_types (code, name, description, is_paid, requires_balance, requires_approval, max_days_per_request)
values
  ('casual', 'Casual Leave', 'Planned personal time off.', true, true, true, 5),
  ('sick', 'Sick Leave', 'Medical or health-related leave.', true, true, true, null),
  ('earned', 'Earned Leave', 'Accrued annual or privilege leave.', true, true, true, 15),
  ('unpaid', 'Unpaid Leave', 'Loss-of-pay leave when paid balance is unavailable.', false, false, true, null)
on conflict (code) do update
set
  name = excluded.name,
  description = excluded.description,
  is_paid = excluded.is_paid,
  requires_balance = excluded.requires_balance,
  requires_approval = excluded.requires_approval,
  max_days_per_request = excluded.max_days_per_request,
  is_active = true;

insert into public.leave_policies (leave_type_code, annual_allowance, min_notice_days, max_carry_forward, carry_forward_allowed)
values
  ('casual', 12, 1, 0, false),
  ('sick', 10, 0, 0, false),
  ('earned', 15, 7, 5, true),
  ('unpaid', 0, 2, 0, false)
on conflict do nothing;

alter table public.leave_types enable row level security;
alter table public.leave_policies enable row level security;
alter table public.holidays enable row level security;

drop policy if exists "leave types readable by authenticated users" on public.leave_types;
drop policy if exists "admins manage leave types" on public.leave_types;
drop policy if exists "leave policies readable by authenticated users" on public.leave_policies;
drop policy if exists "admins manage leave policies" on public.leave_policies;
drop policy if exists "holidays readable by authenticated users" on public.holidays;
drop policy if exists "admins manage holidays" on public.holidays;

create policy "leave types readable by authenticated users"
on public.leave_types for select
to authenticated
using (is_active = true or app_private.is_admin());

create policy "admins manage leave types"
on public.leave_types for all
to authenticated
using (app_private.is_admin())
with check (app_private.is_admin());

create policy "leave policies readable by authenticated users"
on public.leave_policies for select
to authenticated
using (is_active = true or app_private.is_admin());

create policy "admins manage leave policies"
on public.leave_policies for all
to authenticated
using (app_private.is_admin())
with check (app_private.is_admin());

create policy "holidays readable by authenticated users"
on public.holidays for select
to authenticated
using (
  department_id is null
  or app_private.is_admin()
  or exists (
    select 1
    from public.users profile
    where profile.auth_user_id = auth.uid()
      and profile.department_id = holidays.department_id
  )
);

create policy "admins manage holidays"
on public.holidays for all
to authenticated
using (app_private.is_admin())
with check (app_private.is_admin());
