-- Community announcements feed.
-- Admins create/edit/delete/deactivate announcements; all authenticated users read
-- active ones (admins read all, including deactivated). RLS reuses the non-recursive
-- app_private security-definer helpers introduced in the RLS-recursion fix migration.

create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  author_id bigint not null references public.users(id),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_announcements_author_id on public.announcements(author_id);
create index if not exists idx_announcements_created_at on public.announcements(created_at);

alter table public.announcements enable row level security;

drop policy if exists "authenticated read active announcements" on public.announcements;
drop policy if exists "admins read all announcements" on public.announcements;
drop policy if exists "admins insert announcements" on public.announcements;
drop policy if exists "admins update announcements" on public.announcements;
drop policy if exists "admins delete announcements" on public.announcements;

-- Everyone authenticated can read active announcements.
create policy "authenticated read active announcements"
on public.announcements for select
to authenticated
using (is_active = true);

-- Admins can read every announcement (including deactivated).
create policy "admins read all announcements"
on public.announcements for select
to authenticated
using (app_private.is_admin());

create policy "admins insert announcements"
on public.announcements for insert
to authenticated
with check (app_private.is_admin());

create policy "admins update announcements"
on public.announcements for update
to authenticated
using (app_private.is_admin())
with check (app_private.is_admin());

create policy "admins delete announcements"
on public.announcements for delete
to authenticated
using (app_private.is_admin());
