-- TeamPulse core schema for Supabase PostgreSQL + Supabase Auth.
-- Auth identities live in auth.users. TeamPulse authorization lives in public.users.role.

create table if not exists public.departments (
  id bigint generated by default as identity primary key,
  name text not null unique,
  code text not null unique,
  manager_id bigint null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique references auth.users(id) on delete cascade,
  full_name text not null,
  email text not null unique,
  role text not null check (role in ('employee', 'manager', 'admin')),
  is_active boolean not null default true,
  manager_id bigint null references public.users(id),
  department_id bigint null references public.departments(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'departments_manager_id_fkey'
  ) then
    alter table public.departments
      add constraint departments_manager_id_fkey
      foreign key (manager_id) references public.users(id);
  end if;
end $$;

create table if not exists public.leave_balances (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  year int not null,
  casual_total int not null default 12,
  casual_used int not null default 0,
  sick_total int not null default 10,
  sick_used int not null default 0,
  earned_total int not null default 15,
  earned_used int not null default 0,
  unpaid_used int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_leave_balance_user_year unique (user_id, year)
);

create table if not exists public.leave_requests (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.users(id),
  manager_id bigint null references public.users(id),
  leave_type text not null check (leave_type in ('casual', 'sick', 'earned', 'unpaid')),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'cancelled')),
  start_date date not null,
  end_date date not null,
  days int not null check (days > 0),
  reason text not null,
  manager_comment text null,
  created_at timestamptz not null default now(),
  decided_at timestamptz null
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  recipient_id bigint not null references public.users(id) on delete cascade,
  notification_type text not null check (notification_type in ('info', 'warning', 'approval', 'rejection')),
  title text not null,
  message text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id bigint null references public.users(id),
  action text not null check (action in ('create', 'update', 'delete', 'approve', 'reject', 'login')),
  entity_type text not null,
  entity_id bigint null,
  old_values jsonb null,
  new_values jsonb null,
  ip_address text null,
  created_at timestamptz not null default now()
);

create index if not exists idx_users_auth_user_id on public.users(auth_user_id);
create index if not exists idx_users_manager_id on public.users(manager_id);
create index if not exists idx_leave_requests_employee_id on public.leave_requests(employee_id);
create index if not exists idx_leave_requests_manager_id on public.leave_requests(manager_id);
create index if not exists idx_leave_requests_status on public.leave_requests(status);
create index if not exists idx_notifications_recipient_id on public.notifications(recipient_id);
create index if not exists idx_audit_logs_actor_id on public.audit_logs(actor_id);

alter table public.users enable row level security;
alter table public.departments enable row level security;
alter table public.leave_balances enable row level security;
alter table public.leave_requests enable row level security;
alter table public.notifications enable row level security;
alter table public.audit_logs enable row level security;

drop policy if exists "users read own profile" on public.users;
drop policy if exists "managers read team profiles" on public.users;
drop policy if exists "admins read all profiles" on public.users;
drop policy if exists "departments readable by authenticated users" on public.departments;
drop policy if exists "employees read own leave balances" on public.leave_balances;
drop policy if exists "managers read team leave balances" on public.leave_balances;
drop policy if exists "admins read all leave balances" on public.leave_balances;
drop policy if exists "employees read own leave requests" on public.leave_requests;
drop policy if exists "employees create own leave requests" on public.leave_requests;
drop policy if exists "managers read team leave requests" on public.leave_requests;
drop policy if exists "admins read all leave requests" on public.leave_requests;
drop policy if exists "users read own notifications" on public.notifications;
drop policy if exists "users update own notifications" on public.notifications;
drop policy if exists "admins read audit logs" on public.audit_logs;

create policy "users read own profile"
on public.users for select
to authenticated
using (auth_user_id = auth.uid());

create policy "managers read team profiles"
on public.users for select
to authenticated
using (
  exists (
    select 1 from public.users manager_profile
    where manager_profile.auth_user_id = auth.uid()
      and manager_profile.role = 'manager'
      and users.manager_id = manager_profile.id
  )
);

create policy "admins read all profiles"
on public.users for select
to authenticated
using (
  exists (
    select 1 from public.users admin_profile
    where admin_profile.auth_user_id = auth.uid()
      and admin_profile.role = 'admin'
  )
);

create policy "departments readable by authenticated users"
on public.departments for select
to authenticated
using (true);

create policy "employees read own leave balances"
on public.leave_balances for select
to authenticated
using (
  exists (
    select 1 from public.users profile
    where profile.id = leave_balances.user_id
      and profile.auth_user_id = auth.uid()
  )
);

create policy "managers read team leave balances"
on public.leave_balances for select
to authenticated
using (
  exists (
    select 1
    from public.users employee_profile
    join public.users manager_profile on manager_profile.id = employee_profile.manager_id
    where employee_profile.id = leave_balances.user_id
      and manager_profile.auth_user_id = auth.uid()
      and manager_profile.role = 'manager'
  )
);

create policy "admins read all leave balances"
on public.leave_balances for select
to authenticated
using (
  exists (
    select 1 from public.users admin_profile
    where admin_profile.auth_user_id = auth.uid()
      and admin_profile.role = 'admin'
  )
);

create policy "employees read own leave requests"
on public.leave_requests for select
to authenticated
using (
  exists (
    select 1 from public.users profile
    where profile.id = leave_requests.employee_id
      and profile.auth_user_id = auth.uid()
  )
);

create policy "employees create own leave requests"
on public.leave_requests for insert
to authenticated
with check (
  exists (
    select 1 from public.users profile
    where profile.id = leave_requests.employee_id
      and profile.auth_user_id = auth.uid()
      and profile.is_active = true
  )
);

create policy "managers read team leave requests"
on public.leave_requests for select
to authenticated
using (
  exists (
    select 1 from public.users manager_profile
    where manager_profile.id = leave_requests.manager_id
      and manager_profile.auth_user_id = auth.uid()
      and manager_profile.role = 'manager'
  )
);

create policy "admins read all leave requests"
on public.leave_requests for select
to authenticated
using (
  exists (
    select 1 from public.users admin_profile
    where admin_profile.auth_user_id = auth.uid()
      and admin_profile.role = 'admin'
  )
);

create policy "users read own notifications"
on public.notifications for select
to authenticated
using (
  exists (
    select 1 from public.users profile
    where profile.id = notifications.recipient_id
      and profile.auth_user_id = auth.uid()
  )
);

create policy "users update own notifications"
on public.notifications for update
to authenticated
using (
  exists (
    select 1 from public.users profile
    where profile.id = notifications.recipient_id
      and profile.auth_user_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.users profile
    where profile.id = notifications.recipient_id
      and profile.auth_user_id = auth.uid()
  )
);

create policy "admins read audit logs"
on public.audit_logs for select
to authenticated
using (
  exists (
    select 1 from public.users admin_profile
    where admin_profile.auth_user_id = auth.uid()
      and admin_profile.role = 'admin'
  )
);
